// admin_mobile/src/pages/lesson/create/Create.jsx
// 引入react
import React, { Component } from 'react';
// 引入组件
import { InputItem, WhiteSpace, WingBlank, Button, Picker, ImagePicker, List } from 'antd-mobile';
// 引入axios
import axios from 'axios';
// 引入校验方法
import { checkNotEmpty } from '../../../tools/validator';

// 定义组件
export default class Create extends Component {
	// 构造函数
	constructor(props) {
		super(props);
		// 状态
		this.state = {
			title: '',
			price: '',
			sales: '',
			img: '',
			type: ''
		}
	}
	// 课程分类数据
	get typeData() {
		return [
			{ label: '高级课程', value: 'super' },
			{ label: '中级课程', value: 'middle' },
			{ label: '初级课程', value: 'easy' },
			{ label: 'React课程', value: 'react' },
			{ label: 'Vue课程', value: 'vue' },
			{ label: 'Angular课程', value: 'angular' }
		]
	}
	// 	请求地址
	get submitUrl() {
		return '/admin/lesson/create'
	}
	// 切换分类
	getType() {
		// 根据当前的type数据，从typeData寻找对应成员的label值
		let obj = this.typeData.find(item => item.value === this.state.type);
		// 如果有该成员,返回其label值，否则返回请选择类型
		return obj ? obj.label : '请选择类型'
	}
	// 提交图片
	uploadImage(files) {
		// console.log(files)
		// 获取上传的文件
		let file = files[files.length - 1].file
		// let file = files.pop().file
		// 模拟表单提交
		let form = new FormData();
		// 添加file字段
		form.append('file', file)
		// 提交数据
		axios
			.post('/admin/lesson/upload', form)
			// 监听数据返回
			.then(({ data }) => {
				// 如果上传成功
				if (data.errno === 0) {
					// 存储图片
					// this.setState({ img: data.data.img })
					this.setState(data.data)
				} else {
					// 提示错误
					alert(data.msg)
				}
			})
	}
	// 提交数据
	submitData() {
		// 解构数据
		let { title, img, price, sales, type } = this.state;
		// 校验数据
		if (
			checkNotEmpty(title) && 
			checkNotEmpty(img) && 
			checkNotEmpty(price) && 
			checkNotEmpty(sales) && 
			checkNotEmpty(type)
		) {
			// 提交数据
			axios
				.post(this.submitUrl, this.state)
				// 监听数据返回
				.then(({ data }) => {
					// 如果提交成功。进入列表页面
					if (data.errno === 0) {
						// 进入列表页面
						this.props.history.replace('/lesson/list/1')
					} else {
						// 提示错误
						alert(data.msg);
					}
				})
		}
	}
	// 渲染
	render() {
		// 解构数据
		let { title, img, price, sales, type } = this.state;
		return (
			<div>
				<WhiteSpace></WhiteSpace>
				<WhiteSpace></WhiteSpace>
				<InputItem placeholder="请输入课程标题" value={title} onChange={title => this.setState({ title })}>课程标题</InputItem>
				<WhiteSpace></WhiteSpace>
				<InputItem placeholder="请输入课程价格" type="number" value={price} onChange={price => this.setState({ price })}>课程价格</InputItem>
				<WhiteSpace></WhiteSpace>
				{/*<Picker data={this.typeData} cols={1} onChange={arr => this.setState({ type: arr[0] })}>
					<List.Item>选择分类&emsp;{this.getType()}</List.Item>
				</Picker>*/}
				<Picker data={this.typeData} cols={1} value={[type]} onChange={arr => this.setState({ type: arr[0] })}>
					<List.Item>选择分类</List.Item>
				</Picker>
				<WhiteSpace></WhiteSpace>
				<InputItem placeholder="请输入课程销量" type="number" value={sales} onChange={sales => this.setState({ sales })}>课程销量</InputItem>
				<WhiteSpace></WhiteSpace>
				<ImagePicker files={img ? [{ url: img }] : []} onChange={this.uploadImage.bind(this)}></ImagePicker>
				<WhiteSpace></WhiteSpace>
				<WhiteSpace></WhiteSpace>
				<WhiteSpace></WhiteSpace>
				<WingBlank>
					<Button type="primary" onClick={this.submitData.bind(this)}>提交</Button>
				</WingBlank>
			</div>
		)
	}
}

// admin_pc/src/pages/lesson/Create.vue
<!-- div>h1.page-title{创建课程}+el-form[model rules label-width]>(el-form-item[prop label]>el-input[v-model placeholder])*5+div.form-btns>el-button[type=success]{提交} -->
<template>
<div>
	<h1 class="page-title">创建课程</h1>
	<!-- <h1 class="page-title">{{$route.fullPath === '/lesson/create' ? '创建课程' : '编辑课程'}}</h1> -->
	<!-- 1 设置model -->
	<!-- 2 设置prop -->
	<!-- 3 设置rules -->
	<!-- 4 设置ref -->
	<!-- 5 提交数据事件回调函数 -->
	<el-form ref="lesson" :model="data" :rules="rules" label-width="150px">
		<el-form-item prop="title" label="课程标题：">
			<el-input v-model="data.title" placeholder="请输入课程标题"></el-input>
		</el-form-item>
		<el-form-item prop="price" label="课程价格：">
			<el-input v-model="data.price" placeholder="请输入课程价格" type="number"></el-input>
		</el-form-item>
		<el-form-item prop="type" label="课程分类：">
			<!-- 课程分类下拉框 -->
			<el-select v-model="data.type" placeholder="请选择课程分类">
				<el-option v-for="item in types" :label="item.label" :value="item.value" :key="item.value"></el-option>
			</el-select>
		</el-form-item>
		<el-form-item prop="sales" label="课程销量：">
			<el-input v-model="data.sales" placeholder="请输入课程销量" type="number"></el-input>
		</el-form-item>
		<el-form-item prop="img" label="课程图片：">
			<el-upload
				action="/admin/lesson/upload"
				:show-file-list="false"
				:on-success="uploadSuccess"
				:on-error="uploadError"
			>
				<el-button type="primary">上传</el-button>
				<span slot="tip" class="form-upload-tip">请选择上传的图片</span>
			</el-upload>
			<!-- 有数据再渲染图片 -->
			<img class="form-upload-img" :src="data.img" v-if="data.img" alt="">
		</el-form-item>
		<div class="form-btns">
			<el-button type="success" @click="submitData">提交</el-button>
		</div>
	</el-form>
</div>
</template>
<script type="text/javascript">
// 引入校验算法
import { checkNotEmpty } from '../../tools/validator';
// 组件
export default {
	// 数据
	data() {
		// 定义非空校验对象
		let notEmpty = [ { validator: checkNotEmpty, trigger: 'blur' } ];
		// let notEmpty = [ { validator: checkNotEmpty.bind(this, '传递数据'), trigger: 'blur' } ];
		// let notEmpty = [ { validator: (...arg) => checkNotEmpty('hello', ...arg), trigger: 'blur' } ];
		return {
			// 绑定的数据
			data: {},
			// 课程分类
			types: [
				{ label: '高级课程', value: 'super' },
				{ label: '中级课程', value: 'middle' },
				{ label: '初级课程', value: 'easy' },
				{ label: 'React课程', value: 'react' },
				{ label: 'Vue课程', value: 'vue' },
				{ label: 'Angular课程', value: 'angular' }
			],
			// 校验规则
			rules: {
				title: notEmpty,
				price: notEmpty,
				sales: notEmpty,
				type: notEmpty,
				img: notEmpty
			}
		}
	},
	// 定义方法
	methods: {
		// 上传成功
		uploadSuccess(res) {
			// console.log(arguments)
			// 如果成功
			if (res.errno === 0) {
				// 存储数据
				// return this.data.img = res.data.img
				// 避免数据丢失
				return this.$set(this.data, 'img', res.data.img)
			} 
			// 提示错误
			alert(res.msg)
		},
		// 上传失败
		uploadError() {
			console.log('error')
		},
		// 提交数据
		submitData() {
			// 校验表单
			this.$refs.lesson.validate(valid => {
				// 如果校验成功
				if (valid) {
					// 提交数据
					this.$http
						// 添加数据
						.post('/admin/lesson/create', this.data)
						// 监听数据返回
						.then(({ data }) => {
							// 如果创建成功
							if (data.errno === 0) {
								// 进入列表页查看
								this.$router.replace('/lesson/list/1')
							} else {
								// 提示错误
								alert(data.msg)
							}
						})
				}
			})
		}
	},
	// 创建完成
	// created() {
	// 	// 解构数据
	// 	let { params } = this.$route;
	// 	// 发送请求
	// 	this.$http
	// 		.get('/admin/lesson/detail', { params })
	// 		// 监听数据返回
	// 		.then(({ data }) => {
	// 			if (data.errno === 0) {
	// 				// 存储数据
	// 				this.data = data.data;
	// 			}
	// 		})
	// }
}
</script>
